name: "ts-commit-action"
description: "git commit and git push in GitHub Actions"
runs:
  using: composite
  steps:
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Deno Run
      shell: bash
      run: deno run main.ts
